name: Refresh

on:
  schedule: 
      - cron: '*/1 * * * *'
  # push:
  #   branches: main

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Trigger an empty commit to rebuild page
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m 'rebuild pages' --allow-empty
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          USER_TOKEN: ${{ secrets.USER_TOKEN }} 